# 服务配置
server:
  port: 7707

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
  rabbitmq:
    host: 127.0.0.1
    port: 5682
    username: root
    password: 123456
    virtual-host: chat

minio:
  endpoint: http://127.0.0.1:8000 # MinIO服务地址
  fileHost: http://127.0.0.1:8000 # 文件地址host
  bucketName: wechat  # 存储桶bucket名称
  accessKey: minioRoot  # 账号
  secretKey: 123456789  # 密码