# 服务配置
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1 # 不限制请求体大小

# 日志级别
logging:
  level:
    root: info

spring:
  application:
    name: auth-service
  profiles:
    active: dev # dev-开发环境；prod-生产环境；test-测试环境

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      update-strategy: not_empty
    banner: false
  mapper-locations: classpath*:/mappers/*.xml