# 服务配置
server:
  port: 8808

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 5379
      database: 0
      password:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos